# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_JobListTest.ui'
#
# Created: Thu Mar 28 13:08:11 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1217, 328)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.jobTable = QtGui.QTableWidget(self.layoutWidget)
        self.jobTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.jobTable.setObjectName(_fromUtf8("jobTable"))
        self.jobTable.setColumnCount(3)
        self.jobTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.jobTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.jobTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.jobTable.setHorizontalHeaderItem(2, item)
        self.jobTable.horizontalHeader().setVisible(True)
        self.jobTable.horizontalHeader().setStretchLastSection(True)
        self.jobTable.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.jobTable, 1, 0, 1, 7)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 6)
        self.jobTableLabel = QtGui.QLabel(self.layoutWidget)
        self.jobTableLabel.setObjectName(_fromUtf8("jobTableLabel"))
        self.gridLayout.addWidget(self.jobTableLabel, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.killJobButton = QtGui.QPushButton(self.groupBox_2)
        self.killJobButton.setObjectName(_fromUtf8("killJobButton"))
        self.gridLayout_5.addWidget(self.killJobButton, 1, 0, 1, 1)
        self.refreshButton = QtGui.QPushButton(self.groupBox_2)
        self.refreshButton.setObjectName(_fromUtf8("refreshButton"))
        self.gridLayout_5.addWidget(self.refreshButton, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 2, 0, 1, 2)
        self.groupBox_4 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.prioritySetButton = QtGui.QPushButton(self.groupBox_4)
        self.prioritySetButton.setObjectName(_fromUtf8("prioritySetButton"))
        self.gridLayout_7.addWidget(self.prioritySetButton, 1, 1, 1, 1)
        self.prioritySpinBox = QtGui.QSpinBox(self.groupBox_4)
        self.prioritySpinBox.setMaximum(999)
        self.prioritySpinBox.setProperty("value", 50)
        self.prioritySpinBox.setObjectName(_fromUtf8("prioritySpinBox"))
        self.gridLayout_7.addWidget(self.prioritySpinBox, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 2, 2, 1, 2)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 28))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.killTaskButton = QtGui.QPushButton(self.groupBox)
        self.killTaskButton.setObjectName(_fromUtf8("killTaskButton"))
        self.gridLayout_4.addWidget(self.killTaskButton, 1, 0, 1, 1)
        self.resurrectTaskButton = QtGui.QPushButton(self.groupBox)
        self.resurrectTaskButton.setObjectName(_fromUtf8("resurrectTaskButton"))
        self.gridLayout_4.addWidget(self.resurrectTaskButton, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.taskTable = QtGui.QTableWidget(self.layoutWidget1)
        self.taskTable.setEnabled(True)
        self.taskTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.taskTable.setGridStyle(QtCore.Qt.SolidLine)
        self.taskTable.setObjectName(_fromUtf8("taskTable"))
        self.taskTable.setColumnCount(7)
        self.taskTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(6, item)
        self.taskTable.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.taskTable, 1, 0, 1, 4)
        self.taskTableLabel = QtGui.QLabel(self.layoutWidget1)
        self.taskTableLabel.setObjectName(_fromUtf8("taskTableLabel"))
        self.gridLayout_2.addWidget(self.taskTableLabel, 0, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.taskIDLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.taskIDLineEdit.setObjectName(_fromUtf8("taskIDLineEdit"))
        self.gridLayout_6.addWidget(self.taskIDLineEdit, 0, 0, 1, 1)
        self.advancedSearchButton = QtGui.QPushButton(self.groupBox_3)
        self.advancedSearchButton.setObjectName(_fromUtf8("advancedSearchButton"))
        self.gridLayout_6.addWidget(self.advancedSearchButton, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 2, 2, 1, 1)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.jobTableLabel.setBuddy(self.jobTable)
        self.taskTableLabel.setBuddy(self.jobTable)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.jobTable.setSortingEnabled(True)
        item = self.jobTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Job ID", None, QtGui.QApplication.UnicodeUTF8))
        item = self.jobTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Priority", None, QtGui.QApplication.UnicodeUTF8))
        item = self.jobTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Job name", None, QtGui.QApplication.UnicodeUTF8))
        self.jobTableLabel.setText(QtGui.QApplication.translate("MainWindow", "Job List", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Job Options", None, QtGui.QApplication.UnicodeUTF8))
        self.killJobButton.setText(QtGui.QApplication.translate("MainWindow", "Kill", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshButton.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Change Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.prioritySetButton.setText(QtGui.QApplication.translate("MainWindow", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Subtask Options", None, QtGui.QApplication.UnicodeUTF8))
        self.killTaskButton.setText(QtGui.QApplication.translate("MainWindow", "Kill", None, QtGui.QApplication.UnicodeUTF8))
        self.resurrectTaskButton.setText(QtGui.QApplication.translate("MainWindow", "Resurrect", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTable.setSortingEnabled(True)
        item = self.taskTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Task ID", None, QtGui.QApplication.UnicodeUTF8))
        item = self.taskTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Priority", None, QtGui.QApplication.UnicodeUTF8))
        item = self.taskTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Host", None, QtGui.QApplication.UnicodeUTF8))
        item = self.taskTable.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        item = self.taskTable.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Start Time", None, QtGui.QApplication.UnicodeUTF8))
        item = self.taskTable.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "End Time", None, QtGui.QApplication.UnicodeUTF8))
        item = self.taskTable.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("MainWindow", "Duration", None, QtGui.QApplication.UnicodeUTF8))
        self.taskTableLabel.setText(QtGui.QApplication.translate("MainWindow", "Task List (job: none selected)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.taskIDLineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Type TaskID, press Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.advancedSearchButton.setText(QtGui.QApplication.translate("MainWindow", "Advanced...", None, QtGui.QApplication.UnicodeUTF8))

